objetos_busqueda: [["Baliza_arriba",1550, 1550, 850,1000], ["Baliza_abajo",1540, 1540, -900,-1000],["Baliza_intermedia",-1540, -1540, 25,-25],["Torre", -150 , 150, 1000,  1000]]
objetos_busqueda_sucio: [1550,900, 1550, -900,-1540, 0, 0, 1000]
objetos_triangulacion: [["Baliza_arriba",1550, 900], ["Baliza_abajo",1560, -900],["Baliza_intermedia",-1550, 0],["Torre", 0,  1000]]
objetos_eliminables: [["Estanteria_aliada",600, 950], ["Estanteria_enemiga",-600, 950]]


